CREATE OR REPLACE TYPE DIRECCION AS OBJECT (
    CALLE VARCHAR2(25), 
    NUMERO NUMBER, 
    CIUDAD VARCHAR2(20), 
    PAIS VARCHAR2(25)
);

CREATE OR REPLACE TYPE APELLIDOS AS VARRAY(2) OF VARCHAR2(15);
CREATE OR REPLACE TYPE PERSONA AS OBJECT (
    ID NUMBER, 
    NOMBRE VARCHAR2(25), 
    APELLIDOS_ APELLIDOS, 
    FECHA_NAC DATE, 
    PROFESION VARCHAR2(15), 
    DIR DIRECCION
) NOT FINAL;

CREATE OR REPLACE TYPE ARTISTA UNDER PERSONA (
    PAIS_PROCEDENCIA VARCHAR2(15), 
    GENERO_RECURRENTE VARCHAR2(10), 
    GRUPO_NOMBRE VARCHAR2(15), 
    ANYO_LANZAMIENTO_PRIMER_ALBUM NUMBER(4)
);

CREATE OR REPLACE TYPE CANCION AS OBJECT (
    TITULO VARCHAR2(25), 
    ID_ARTISTA REF ARTISTA,
    LETRA CLOB, 
    ID_ALBUM NUMBER,
    SINGLE NUMBER(1), 
    DURACION FLOAT, 
    COLABORADOR REF ARTISTA
);

CREATE TYPE CANCIONES_ALBUM AS TABLE OF CANCION;
CREATE OR REPLACE TYPE ALBUM AS OBJECT (
    ID NUMBER,
    AUTOR REF ARTISTA, 
    NOMBRE VARCHAR2(25), 
    FECHA_PUBLICACION DATE, 
    RANKING_MAX NUMBER, 
    CANCIONES_ALB CANCIONES_ALBUM
);

CREATE OR REPLACE TYPE ACADEMIA AS OBJECT (
    CIF VARCHAR2(9), 
    NOMBRE VARCHAR2(25), 
    UBICACION_PRINCIPAL VARCHAR2(25), 
    DIRIGENTE REF PERSONA, 
    FECHA_FUNDACION DATE
);

CREATE OR REPLACE TYPE JURADO AS OBJECT (
    ID NUMBER,
    ID_CATEGORIA NUMBER,
    ID_PERSONA REF PERSONA
);
CREATE OR REPLACE TYPE JURADO_MIEMBROS AS VARRAY(2) OF JURADO;




CREATE OR REPLACE TYPE NOMINACION AS OBJECT (
    ID NUMBER, 
    ID_CATEGORIA NUMBER,
    ID_CANCION REF CANCION
);
CREATE OR REPLACE TYPE CANCIONES_NOMINADAS AS VARRAY(3) OF NOMINACION;




CREATE OR REPLACE TYPE CATEGORIA AS OBJECT (
    ID NUMBER, 
    ACADEMIA_ REF ACADEMIA,
    NOMBRE_PREMIACION VARCHAR2(25),
    NOMBRE VARCHAR2(25),
    PREMIO_EFECTIVO FLOAT, 
    GANADOR REF ARTISTA, 
    FECHA_FIN_VOTACION DATE, 
    JURADOS JURADO_MIEMBROS,
    NOMINADAS CANCIONES_NOMINADAS
);
CREATE TYPE CATEGORIAS_TIPO_ANIDADA AS TABLE OF CATEGORIA;




CREATE OR REPLACE TYPE PREMIACION AS OBJECT (
    ID NUMBER,
    ACADEMIA_ REF ACADEMIA, 
    NOMBRE VARCHAR2(25), 
    FECHA_EVENTO DATE, 
    CATEGORIAS_TABLA CATEGORIAS_TIPO_ANIDADA
);

CREATE OR REPLACE TYPE INVITADO AS OBJECT (
    ID NUMBER,
    ID_PERSONA REF PERSONA, 
    ACADEMIA_ REF ACADEMIA, 
    PREMIOS REF PREMIACION
);




CREATE OR REPLACE TYPE CANCION_PRESENTADA AS OBJECT (
    ID NUMBER,
    ID_PRESENTACION NUMBER,
    CANCION_P REF CANCION
);


CREATE OR REPLACE TYPE BAILARIN AS OBJECT (
    ID NUMBER, 
    ID_PRESENTACION NUMBER, 
    ID_PERSONA REF PERSONA
);

CREATE OR REPLACE TYPE BAILARINES AS VARRAY(12) OF BAILARIN;
CREATE OR REPLACE TYPE CANCIONES_PRESENTADAS AS VARRAY(3) OF CANCION_PRESENTADA;

CREATE OR REPLACE TYPE PRESENTACION AS OBJECT (
    ID_PRESENTACION NUMBER, 
    ID_ARTISTA REF ARTISTA, 
    PREMIO REF PREMIACION,
    ORDEN_ACTUACION NUMBER,
    DURACION FLOAT, 
    ATREZZO CLOB, 
    CANCIONES CANCIONES_PRESENTADAS, 
    GRUPO_BAILE BAILARINES
);




CREATE TABLE PERSONAS OF PERSONA (
    ID PRIMARY KEY
);
CREATE TABLE ARTISTAS OF ARTISTA (
    ID PRIMARY KEY
);

CREATE TABLE ALBUMES OF ALBUM (
    ID PRIMARY KEY
) NESTED TABLE CANCIONES_ALB STORE AS CANCIONES_ANIDADA;

CREATE TABLE CANCIONES OF CANCION (
    TITULO PRIMARY KEY
);

CREATE TABLE ACADEMIAS OF ACADEMIA (
    CIF PRIMARY KEY
);

CREATE TABLE JURADOS OF JURADO (
    ID PRIMARY KEY
);

CREATE TABLE NOMINACIONES OF NOMINACION (
    ID PRIMARY KEY
);

CREATE TABLE PREMIACIONES OF PREMIACION (
    ID PRIMARY KEY
) NESTED TABLE CATEGORIAS_TABLA STORE AS CATEGORIAS_ANIDADA;

CREATE TABLE INVITADOS OF INVITADO (
    ID PRIMARY KEY
);

CREATE TABLE CATEGORIAS OF CATEGORIA (
    ID PRIMARY KEY
);

CREATE TABLE CS_PRESENTADAS OF CANCION_PRESENTADA;

CREATE TABLE BAILARINES_PRESENTADOS OF BAILARIN (
    ID PRIMARY KEY
);

CREATE TABLE PRESENTACIONES OF PRESENTACION (
    ID_PRESENTACION PRIMARY KEY
);