SET SERVEROUTPUT ON;

DECLARE
    CURSOR CATEGORIAS_ORDENADAS IS
        SELECT C.ID FROM CATEGORIAS C;
    
    CURSOR JURADOS_CATEGORIAS IS
        SELECT J.ID, J.ID_CATEGORIA, J.ID_PERSONA FROM JURADOS J;
    
    JURADO_CATEGORIAS JURADO_MIEMBROS := JURADO_MIEMBROS();    
    JURADO_CATEGORIA JURADO;
    
    MIEMBROS NUMBER;
    ID_CAT NUMBER;
BEGIN
    MIEMBROS := 0;
    FOR CAT IN CATEGORIAS_ORDENADAS LOOP
        ID_CAT := CAT.ID;
        
        FOR I IN JURADOS_CATEGORIAS LOOP
            IF ID_CAT = I.ID_CATEGORIA THEN
                JURADO_CATEGORIA := JURADO(I.ID, I.ID_CATEGORIA, I.ID_PERSONA);
                MIEMBROS := MIEMBROS + 1;
        
                IF MIEMBROS <= 2 THEN
                    JURADO_CATEGORIAS.EXTEND;
                    JURADO_CATEGORIAS(JURADO_CATEGORIAS.LAST) := JURADO_CATEGORIA;
                    
                    UPDATE CATEGORIAS C SET C.JURADOS = JURADO_CATEGORIAS WHERE C.ID = ID_CAT;
                    COMMIT;
                ELSE
                    JURADO_CATEGORIAS := JURADO_MIEMBROS(); 
                    MIEMBROS := 0;
                END IF;
            END IF;
        END LOOP;
    END LOOP;
END;